spec:
  template:
    spec:
      serviceAccountName: csc-shouv-jenkins
      initContainers:
        - name: copy-default-config
          volumeMounts:
            - mountPath: /var/jenkins_jobs/jobs/test-jenkins
              name: csc-shouv-jenkins-job-test-jenkins-volume
      volumes:
      - name: csc-shouv-jenkins-job-test-jenkins-volume
        configMap:
          name: csc-shouv-jenkins-job-test-jenkins
          items:
          - key: config.xml
            path: config.xml
          - key: build-config.xml
            path: jobs/Build/config.xml
          - key: build-state.xml
            path: jobs/Build/state.xml